name: Yad2 Apartment Notifier Bot
on:
  schedule:
    - cron: '0 * * * *' # Runs once an hour
  workflow_dispatch: # Allows manual triggering
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Check if unique_links.json exists or create a new one
    - name: Check for Existing Data
      run: |
        if [ ! -f unique_links.json ]; then
          echo "unique_links.json not found, creating a new file."
          echo "[]" > unique_links.json
        fi

    - name: Run Yad2 Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID_USER: ${{ secrets.CHAT_ID_USER }}
        CHAT_ID_YOTAM: ${{ secrets.CHAT_ID_YOTAM }}
      run: |
        source venv/bin/activate
        python main.py --neighborhoods neighborhoods.json

    - name: Commit unique_links.json to the repository
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add unique_links.json
        git commit -m "Update unique_links.json after bot run" || echo "No changes to commit"
        git push https://x-access-token:${PAT_TOKEN}@github.com/RoyBidani/Yad2SearchBot.git main
