name: Yad2 Apartment Notifier Bot
on:
  schedule:
    - cron: '0 * * * *' # Runs once an hour
  workflow_dispatch: # Allows manual triggering
jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Check if unique_date_added.json exists or create a new one
    - name: Check for Existing Data
      run: |
        if [ ! -f unique_date_added.json ]; then
          echo "unique_date_added.json not found, creating a new file."
          echo "[]" > unique_date_added.json
        fi

    - name: Run Yad2 Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID_USER: ${{ secrets.CHAT_ID_USER }}
        CHAT_ID_YOTAM: ${{ secrets.CHAT_ID_YOTAM }}
      run: |
        source venv/bin/activate
        python main.py --neighborhoods neighborhoods.json

    # Commit and push updated unique_date_added.json back to the repository
    - name: Commit unique_date_added.json to the repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add unique_date_added.json
        git commit -m "Update unique_date_added.json after bot run"
        git push origin main
