name: Yad2 Apartment Notifier Bot
on:
  schedule:
    - cron: '0 * * * *' # Runs once an hour
  workflow_dispatch: # Allows manual triggering
jobs:
  run-bot:
    runs-on: ubuntu-latest
    concurrency: yad2bot
    permissions:
      contents: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        playwright install --with-deps chromium

    - name: Run Yad2 Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CHAT_ID_USER: ${{ secrets.CHAT_ID_USER }}
      run: python main.py

    - name: Commit sent_posts.json to the repository
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add sent_posts.json
        git commit -m "Update sent_posts.json after bot run" || echo "No changes to commit"
        git push
